[package]
name = "lb"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
ntex = { version = "2.0.3", features = ["tokio"] }
simple_logger = "5.0.0"
tokio = { version = "1.38.0", features = ["full"] }
